### ISSUE TITLE
Want to collaborate?

### ISSUE THREAD

**Issue by ErioirE** [jessegranger/AssistantMod#1]
Hello, I'm a C# developer and I've been using ExileAPI off and on for a few years. It's decent but it has a bunch of issues and I feel it would be fun to make plugins for it. The problem is I'm not that familiar with many of the platforms and libraries it uses since most of my coding is for non-GUI professional applications. 
I was hoping I could pick your brain about how ExileAPI performs its various processes.

Discord: Erioire#9582

Thanks,
David

**Comment by jessegranger** [comment]
Thanks for reaching out, and yeah I can share what I know, which maybe isn't all that much.

I am hoping that a dev community can come together now that @Queuete has decided to stop maintaining his branch.

They are working on my internet today, but I will hop on your discord when I get the chance.

**Comment by ErioirE** [comment]
Cool, I'm looking forward to it!

**Comment by jessegranger** [comment]
Wanted to let you know I just made public my new project, a complete rewrite of ExileApi: https://github.com/jessegranger/AtE/
Has working offsets, and ability to make plugins (as PRs for now). Since I wrote this one from the ground up, I would definitely be able to answer questions about it.
